### ISSUE TITLE
declarative demography: yaml? something else?

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#10]
Following on from the discussion in the msprime repo: https://github.com/tskit-dev/msprime/issues/1058

`demes` can do round trip dump/load to/from a yaml file (see `tests/test_examples.py`). But I don't really like yaml: its just too complex, has confusing behaviour in many edge cases, and behaviour varies among implementations (https://www.google.com/search?q=yaml+criticism). I used [strictyaml](https://github.com/crdoconnor/strictyaml) for the implementation here, which attempts to overcome yaml's problems by applying a schema to support a strict subset of yaml. But strictyaml is a python package (and in particular, the schema can be described in python only). So non-python consumers of `demes` scripts will likely import using a general purpose yaml parser, and thus inherit all the regular yaml problems.

Can we do better?

**Comment by jeromekelleher** [comment]
I'm happy to consider a yaml-like DSL for this, but yaml has a lot of advantages. Since the main goal of this package is to take a high-level human-readable description (== yaml, currently) and transform it into a low-level, unambiguous description (a Python object model, or JSON description) that can be consumed by other programs, I'm not so worried about cross language support for the high-level description. So, if strictyaml does what we need, then I'd not see much reason to use anything else for now.

I.e., for interfacing with something like SLiM, we could imagine writing the low-level JSON format to file, which SLiM would provide an Eidos function to read and make a model with. It doesn't need to know anything about yaml.

**Comment by grahamgower** [comment]
Closing this because I think we have too much momentum with the existing yaml format to want to change it now.
