### ISSUE TITLE
Time goes forward or backward or both?

### ISSUE THREAD

**Issue by jeromekelleher** [grahamgower/demes#11]
A fundamental choice we need to make is what direction we see time going in. Having tried to document a backwards-in-time description for several years now, I'm pretty convinced that talking about population processes backwards in time is an inherently confusing thing, even to experts, who still make mistakes. IMO, the goal we should aim for is a simple and intuitive description of population processes forwards in time, with concrete and unambiguous language to define the various concepts. Given this unambiguous description, it'll be simple enough for things that work in backwards time (like msprime) to translate into their own internal models.

There is the issue of when we make the reference time, i.e., when is zero. I don't think this is much of an issue, really - it's just an arbitrary time that we measure differences from, and can be left to the user. They can make the present day be time zero, if they like, and make events using negative times. Or, we could make the reference time the present, and state that units are in "year ago". It really doesn't matter that much, and we can easily have a flag to sort out how that works.

For things like migration, I don't think we can avoid using terminology like ``source`` and ``destination``, because individuals really do come *from* somewhere and go *to* somewhere else. These concepts from ``from`` and ``to`` should be in the forwards-time sense, because the backwards sense is very confusing.

**Comment by jeromekelleher** [comment]
That's my opinion though - what do others think?!

**Comment by grahamgower** [comment]
I agree that time should flow forwards, such that we have `start_time < end_time`, or `early_time < late_time`. However, describing models using "years ago", or kya, seems very natural to me. And I reckon its a bad idea to require that a user identify the oldest time in their model and translate all other times to be relative to this, each time they write a yaml file. So making `T_now=0` and using negative times for the past seems like a nice practical solution.

Just how jarring is it to use negative numbers here though? Presumably the most obvious error would be to forget, and use positive numbers where a negative number is intended. Is there any reason to permit the use of both positive and negative times in a single demography?

**Comment by apragsdale** [comment]
So it sounds like we next need to settle on a convention for measuring time, now that we're happy with the direction of time flowing from past to present (forward time convention). Having negative time I think can be confusing, and anchoring at time other than present I also find less convenient or clear. My current PR has time measure in time units back from present, so it checks that the start of an epoch is older than the end of the epoch, e.g. I personally prefer this option for now, but happy to discuss alternatives or be persuaded otherwise :)

**Comment by grahamgower** [comment]
I think that's a fine convention. How did you imagine specifying a forwards time demography that matches an "experimental evolution" type study (sorry, I don't know the correct terminology for this)? In this case, the model writer would have to put time zero at the end of their study, which seems wrong to me, particularly if the experiment has not been run. I guess whatever choice we make, it will be less than ideal for some types of models.

Also, I'm convinced we should change the terms "start_time" and "end_time" to something else, if only to avoid confusion due to these terms being used differently in the msprime API.

**Comment by molpopgen** [comment]
For experimental evolution, having time zero be the end has the same meaning as for other models--"the final sampling point".

**Comment by grahamgower** [comment]
To summarise: time flows forwards, time=0 means the present, and start_time > end_time. This implies that source/dest for migrations has the forward-time convention: a migrant is born in 'source' and has offspring in 'dest'.
