### ISSUE TITLE
DemeGraph.get_demographic_events()

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#96]
This method classifies ancestor/descendant relationships into `split`/`branch`/`admix`/`merge` types. These classifications are currently used by the `moments` conversion code, but might be more widely useful. However, `get_demographic_events()` only gets called on a deme graph when a yaml file is loaded, in `demes.loads()`. So if one wishes to instead use the python API to construct a graph, then one must first call `get_demographic_events()` onself before using the `SFS()` moments conversion fuction. Perhaps `demes.convert.SFS()` should be calling this method itself? I also wonder if `get_demographic_events()` should instead return the splits/branches/admixtures/mergers lists instead of these being attributes of the graph? And maybe we could rename the method? `classify_graph_vertices()`?

**Comment by apragsdale** [comment]
That could make sense, or perhaps `list_demographic_events` if we change the behavior to return lists of all discrete demographic events. Or even just `g.demographic_events()` returns a dictionary of event types as keys and lists of events as values.

I'm realizing now, though, that the behavior is wrong. Currently, if I call `g.get_demographic_events()` more than once, events get added multiple times to those lists instead of being cleared before populating them. Or if an event is already in one of the lists, it gets added again. That would need to be fixed if we don't change the behavior here.

**Comment by apragsdale** [comment]
Closed by #110
